# -*- coding: utf-8 -*-
DAYS = [
{"key":"dom","dow":0,"name":"Domingo","kind":"rest","title":"Descanso absoluto","focus":"Ni pesas ni carrera",
 "lead":"Recuperación total: es cuando el sistema nervioso y las articulaciones se reparan. Una sola noche de mal sueño puede bajar tu síntesis de proteínas un 18 %.",
 "ex":[]},
{"key":"lun","dow":1,"name":"Lunes","kind":"torso","title":"Torso A","focus":"Pecho · Espalda · Hombro · Brazos",
 "lead":"Sesión única. Toda la energía para empujes y tracciones de torso.",
 "ex":[
  {"g":"Pecho","n":"Press inclinado con mancuernas","alt":"o multipower, ~15° de inclinación","s":3,"r":"6-12","rir":"RIR 1-2","k":"press_inclinado",
   "cue":"Parte de una ligera retracción escapular y expande la caja torácica. El press es una aducción muy eficaz para el pecho; mejor que las aperturas, donde el bíceps se activa de más y limita antes de que el pectoral llegue a su estímulo máximo."},
  {"g":"Espalda alta","n":"Remo apoyado en el pecho","alt":"trapecios, romboides y deltoides posterior","s":3,"r":"8-12","rir":"RIR 1-2","k":"remo_pecho_apoyado",
   "cue":"El apoyo en el pecho elimina la fatiga lumbar y de otras articulaciones: te concentras puramente en traccionar."},
  {"g":"Hombro lateral","n":"Elevaciones laterales","alt":"mejor en polea que con mancuernas","s":3,"r":"12-15","rir":"RIR 0","k":"elevaciones_laterales",
   "cue":"El deltoides anterior ya trabaja en los presses y el posterior en los remos: aquí enfócate en la cabeza lateral. Con polea la tensión es constante; a la altura de la cadera enfatizas el inicio del recorrido, donde el músculo está más estirado."},
  {"g":"Bíceps","n":"Curl predicador unilateral","alt":"máximo estímulo en estiramiento","s":3,"r":"10-15","rir":"RIR 0-1","k":"curl_predicador",
   "cue":"Gran estabilidad y excelente alineación. El perfil de resistencia es mayor en la primera mitad del recorrido, justo donde el bíceps está estirado."},
  {"g":"Tríceps","n":"Extensión con hombros neutros","alt":"en polea","s":3,"r":"10-15","rir":"RIR 0-1","k":"ext_triceps_polea",
   "cue":"Movimiento sencillo y estable. Inclínate ligeramente hacia delante para que el cable pase cerca del hombro y este no limite el recorrido."}]},
{"key":"mar","dow":2,"name":"Martes","kind":"pierna","title":"Pierna A","focus":"Foco cuádriceps y glúteo",
 "lead":"Sesión única. Piernas frescas para mover cargas pesadas en prensa y búlgaras.",
 "ex":[
  {"g":"Cuádriceps","n":"Prensa de piernas","alt":"empuje estable, progresión a largo plazo","s":3,"r":"8-15","rir":"RIR 1-2","k":"prensa",
   "cue":"Excelente complemento: genera mucha hipertrofia en los vastos del cuádriceps y el resto del tren inferior, permitiendo empujar con mucha estabilidad."},
  {"g":"Glúteo · Cuádriceps","n":"Sentadilla búlgara","alt":"sujétate con una mano para estabilizar","s":3,"r":"8-12 / pierna","rir":"RIR 1-2","k":"bulgara",
   "cue":"Busca la máxima profundidad y flexión de cadera para que el glúteo trabaje estirado bajo carga. Un punto de apoyo estable te deja aplicar la máxima intensidad sin pelear con el equilibrio."},
  {"g":"Isquios","n":"Curl femoral sentado","alt":"aislamiento","s":3,"r":"10-15","rir":"RIR 0-1","k":"curl_femoral_sentado",
   "cue":"La opción número uno si solo pudieras elegir una: sentado, con la cadera flexionada, los isquios quedan en estiramiento y eso favorece mucho más la hipertrofia que la versión tumbada."},
  {"g":"Pantorrillas","n":"Elevación de talones de pie","alt":"rodilla extendida, + parciales al final","s":4,"r":"12-15","rir":"RIR 0","k":"gemelos_de_pie",
   "cue":"De pie y con la rodilla estirada el gemelo se mantiene elongado y aplica fuerza con eficiencia. La fase de estiramiento es la más importante: al llegar al fallo, sigue con repeticiones parciales abajo."},
  {"g":"Core","n":"Rueda abdominal","alt":"anti-extensión","s":3,"r":"8-15","rir":"Fallo técnico","k":"rueda_abdominal",
   "cue":"Haz una ligera retroversión pélvica (curvar un poco la pelvis hacia dentro, sin chepar en exceso) para proteger la zona lumbar durante todo el recorrido."}]},
{"key":"mie","dow":3,"name":"Miércoles","kind":"run","title":"Carrera suave","focus":"Zona 2 · regenerativo",
 "lead":"Sesión única. 30-40 min de trote a ritmo muy cómodo: deberías poder hablar sin ahogarte.",
 "ex":[{"g":"Running","n":"Trote continuo en Zona 2","alt":"30-40 min · ritmo conversacional","s":1,"r":"30-40 min","rir":"Suave","k":"run_z2",
   "cue":"Día sin pesas. El objetivo es regenerar, no acumular fatiga: si terminas necesitando recuperarte de la carrera, has ido demasiado rápido."}]},
{"key":"jue","dow":4,"name":"Jueves","kind":"torso","title":"Torso B","focus":"Espalda · Pecho · Brazos",
 "lead":"Jornada doble: pesas y running el mismo día. Sepáralas al menos 6 h; si no puedes, pesas primero y a correr 10-15 min después.",
 "double":True,
 "ex":[
  {"g":"Espalda (dorsal)","n":"Jalón al pecho","alt":"o dominadas","s":3,"r":"8-12","rir":"RIR 1-2","k":"jalon_pecho",
   "cue":"Un clásico altamente estable y seguro, ideal para progresar cargas. Los protagonistas son el dorsal y el redondo mayor."},
  {"g":"Pecho","n":"Press plano","alt":"en máquina o con mancuernas","s":3,"r":"8-12","rir":"RIR 1-2","k":"press_plano",
   "cue":"Mismo criterio que el inclinado: ligera retracción escapular de partida y caja torácica expandida durante todo el recorrido."},
  {"g":"Espalda unilateral","n":"Jalón unilateral en polea alta","alt":"extensión de hombro del dorsal","s":3,"r":"10-12 / lado","rir":"RIR 1","k":"jalon_unilateral",
   "cue":"Trabaja específicamente la función de extensión de hombro del dorsal. Añade una ligera rotación al inicio para estirarlo por completo desde su origen."},
  {"g":"Bíceps","n":"Curl Bayesian en polea","alt":"o curl inclinado si las poleas están ocupadas","s":3,"r":"10-15","rir":"RIR 0-1","k":"curl_bayesian",
   "cue":"Partes con el bíceps ya estirado desde la articulación del hombro. Al ser polea, regula la altura para ajustar el perfil de resistencia a tu gusto."},
  {"g":"Tríceps","n":"Extensión Katana","alt":"polea por encima de la cabeza","s":3,"r":"12-15","rir":"RIR 0-1","k":"katana",
   "cue":"Ataca la cabeza larga en estiramiento. Truco de estabilidad: gírate y apoya el codo contra la estructura de la polea para no balancearte."}],
 "run":{"n":"Intervalos o tempo (HIIT)","d":"La segunda sesión del día. Si tu prioridad es ganar músculo, haz las pesas primero. Cuida la proteína y añade una pizca de sal al agua para reponer electrolitos.","k":"run_hiit"}},
{"key":"vie","dow":5,"name":"Viernes","kind":"pierna","title":"Pierna B","focus":"Foco isquios y cadera",
 "lead":"Sesión única. Estímulo pesado de cadena posterior.",
 "ex":[
  {"g":"Isquios · Glúteo","n":"Peso muerto rumano","alt":"barra o mancuernas","s":3,"r":"6-10","rir":"RIR 2","k":"peso_muerto_rumano",
   "cue":"Bisagra de cadera: isquios y glúteo bajo gran tensión de estiramiento, con aductor mayor y espalda baja implicados. Deja margen de RIR 2 por seguridad lumbar."},
  {"g":"Cuádriceps","n":"Extensión de rodilla en máquina","alt":"aislamiento","s":3,"r":"12-15","rir":"RIR 0-1","k":"extension_rodilla",
   "cue":"El ejercicio estrella del cuádriceps: al mantener la cadera fija es el único que estimula de forma óptima el recto femoral, la cabeza que cruza la cadera."},
  {"g":"Glúteo","n":"Hip Thrust","alt":"aislamiento sin cuádriceps","s":3,"r":"8-12","rir":"RIR 1-2","k":"hip_thrust",
   "cue":"Si quieres aislar por completo el glúteo dejando fuera el cuádriceps, es el mejor ejercicio absoluto por su capacidad de progresión de cargas."},
  {"g":"Pantorrillas","n":"Elevación de talones de pie","alt":"rodilla extendida","s":4,"r":"12-15","rir":"RIR 0","k":"gemelos_de_pie",
   "cue":"Insiste en la parte baja del recorrido: la fase de estiramiento es la que más crecimiento aporta."},
  {"g":"Antebrazo","n":"Curl de muñeca sentado","alt":"antebrazo apoyado en el banco","s":3,"r":"15-20","rir":"RIR 0","k":"curl_muneca",
   "cue":"Apoya el brazo en el banco para restringir el movimiento y suelta ligeramente la mancuerna al bajar, así trabajas también la flexión de los dedos al subir."}]},
{"key":"sab","dow":6,"name":"Sábado","kind":"run","title":"Tirada larga","focus":"Resistencia · carrera continua",
 "lead":"Sesión única. Carrera continua para ganar resistencia cardiovascular, sin pesas de por medio.",
 "ex":[{"g":"Running","n":"Tirada larga continua","alt":"ritmo sostenible de principio a fin","s":1,"r":"Larga","rir":"Continuo","k":"run_larga",
   "cue":"Al día siguiente toca descanso absoluto, así que aquí puedes acumular la mayor carga de carrera de la semana."}]},
]
